name: Test

on:
  workflow_dispatch:
  push:
    branches: [ "main", "dev","feature/*","unstable" ]
  pull_request:
    branches: [ "main", "dev","feature/*","unstable" ]

env:
  claudeinsight_log_option: --bpf-event-log-level 5 --conntrack-log-level 5 --agent-log-level 5

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: '1.22.4'

      - name: Build
        run: |
          sudo apt update
          sudo apt install -y git
          sudo apt-get -y install pkg-config
          sudo apt install -y libelf-dev

          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-15 main"
          sudo apt update

          sudo apt install -y llvm
          sudo apt install -y clang
          pwd
          ls -l
          make clean && make build-bpf && make

      # - name: Test
      #   run: make test

      - name: Store executable
        uses: actions/upload-artifact@v4.6.1
        with:
          name: claudeinsight
          path: claudeinsight


  e2e-test:
    name: e2e-test
    needs: build
    strategy:
      fail-fast: false
      matrix:
        kernel:
          # renovate: datasource=docker depName=quay.io/lvh-images/kernel-images
          - '4.19-20240912.022020'
          # renovate: datasource=docker depName=quay.io/lvh-images/kernel-images
          - '5.4-20240912.022020'
          # renovate: datasource=docker depName=quay.io/lvh-images/kernel-images
          - '5.10-20240912.022020'
          # renovate: datasource=docker depName=quay.io/lvh-images/kernel-images
          - '5.15-20240912.022020'
          # renovate: datasource=docker depName=quay.io/lvh-images/kernel-images
          - '6.1-20240912.022020'
          # renovate: datasource=docker depName=quay.io/lvh-images/kernel-images
          - '6.6-20240912.022020'
          # renovate: datasource=docker depName=quay.io/lvh-images/kernel-images
          - 'bpf-20240912.022020'
          # renovate: datasource=docker depName=quay.io/lvh-images/kernel-images
          - 'bpf-next-20240912.022020'
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - name: Retrieve stored claudeinsight executable
        uses: actions/download-artifact@v4.1.9
        with:
          name: claudeinsight
          path: claudeinsight

      - name: Provision LVH VMs
        uses: cilium/little-vm-helper@c44c1221b104ee02ec0235211f7ace3c88eb11a2 # v0.0.19
        with:
          test-name: claudeinsight-test
          image-version: ${{ matrix.kernel }}
          cpu: 2
          mem: '4G'
          host-mount: ./
          install-dependencies: 'true'
          cmd: |
            chmod +x /host/claudeinsight/claudeinsight

      - name: download btf file
        if: ${{ startsWith(matrix.kernel, '4.') }}
        run: |
          img=quay.io/lvh-images/kernel-images:${{ matrix.kernel }} 
          docker pull $img
          id=$(docker create $img)
          mkdir data/
          docker cp $id:/data/kernels data/
          ls -la data/
          find data/ -path "*vmlinuz*" -type f
          find data/ -path "*btf*" -type f

      - name: copy btf file
        if: ${{ startsWith(matrix.kernel, '4.') }}
        uses: cilium/little-vm-helper@c44c1221b104ee02ec0235211f7ace3c88eb11a2 # v0.0.19
        with:
          provision: 'false'
          cmd: |
            uname -a
            cat /etc/issue
            cat /etc/os-release

            sudo mkdir -p /var/lib/claudeinsight/btf/

            sudo cp /host/data/kernels/4.*/boot/btf-4.* /var/lib/claudeinsight/btf/current.btf
            # btf_file=$(find /host/ -path "*btf*" -type f)
            # sudo cp $btf_file /var/lib/ptcpdump/btf/vmlinux

      - name: Install dependencies
        uses: cilium/little-vm-helper@c44c1221b104ee02ec0235211f7ace3c88eb11a2 # v0.0.19
        with:
          provision: 'false'
          cmd: |
            apt-get update
            apt-get install -y dnsutils || true
            apt-get install -y bind9-dnsutils || true
            # install btf
            if [ -f "/sys/kernel/btf/vmlinux" ]; then
              mkdir -p /var/lib/claudeinsight/btf
              cp -f /sys/kernel/btf/vmlinux /var/lib/claudeinsight/btf/current.btf
            fi

            #install python pip
            sudo apt install -y python3 python3-pip pipx

            #install docker-compose
            # apt-get install -y docker-compose-plugin
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version


      - name: Test DNS
        uses: cilium/little-vm-helper@c44c1221b104ee02ec0235211f7ace3c88eb11a2 # v0.0.19
        with:
          provision: 'false'
          cmd: |
            set -euxo pipefail
            uname -a
            cat /etc/issue
            pushd /host
            if [ -f "/var/lib/claudeinsight/btf/current.btf" ]; then  
                bash /host/testdata/test_dns.sh 'sudo /host/claudeinsight/claudeinsight $claudeinsight_log_option --btf /var/lib/claudeinsight/btf/current.btf'
            else  
                bash /host/testdata/test_dns.sh 'sudo /host/claudeinsight/claudeinsight $claudeinsight_log_option'
            fi
            popd

      - name: Test Truncated Data parsing
        uses: cilium/little-vm-helper@c44c1221b104ee02ec0235211f7ace3c88eb11a2 # v0.0.19
        with:
          provision: 'false'
          cmd: |
            set -euxo pipefail
            uname -a
            cat /etc/issue
            pushd /host
            if [ -f "/var/lib/claudeinsight/btf/current.btf" ]; then  
                bash /host/testdata/test_truncated_data.sh 'sudo /host/claudeinsight/claudeinsight $claudeinsight_log_option --btf /var/lib/claudeinsight/btf/current.btf'
            else  
                bash /host/testdata/test_truncated_data.sh 'sudo /host/claudeinsight/claudeinsight $claudeinsight_log_option'
            fi
            popd

      - name: Test CAP_BPF privilege check
        uses: cilium/little-vm-helper@c44c1221b104ee02ec0235211f7ace3c88eb11a2 # v0.0.19
        if: ${{ !contains(fromJSON('["4.19-20240912.022020", "5.4-20240912.022020"]'), matrix.kernel) }}
        with:
          provision: 'false'
          cmd: |
            set -euxo pipefail
            uname -a
            cat /etc/issue
            pushd /host
            bash /host/testdata/run_cap_bpf_test.sh "" "CAP_BPF"
            popd

      - name: Test CAP_SYS_ADMIN privilege check
        uses: cilium/little-vm-helper@c44c1221b104ee02ec0235211f7ace3c88eb11a2 # v0.0.19
        if: contains(fromJSON('["4.19-20240912.022020", "5.4-20240912.022020"]'), matrix.kernel)
        with:
          provision: 'false'
          cmd: |
            set -euxo pipefail
            uname -a
            cat /etc/issue
            pushd /host
            bash /host/testdata/run_cap_bpf_test.sh "" "CAP_SYS_ADMIN"
            popd

      - name: Test filter by comm
        uses: cilium/little-vm-helper@c44c1221b104ee02ec0235211f7ace3c88eb11a2 # v0.0.19
        with:
          provision: 'false'
          cmd: |
            set -euxo pipefail
            uname -a
            cat /etc/issue
            pushd /host
            if [ -f "/var/lib/claudeinsight/btf/current.btf" ]; then
                bash /host/testdata/test_filter_by_comm.sh 'sudo /host/claudeinsight/claudeinsight $claudeinsight_log_option --btf /var/lib/claudeinsight/btf/current.btf'
            else
                bash /host/testdata/test_filter_by_comm.sh 'sudo /host/claudeinsight/claudeinsight $claudeinsight_log_option'
            fi
            popd

      - name: Test gotls
        uses: cilium/little-vm-helper@c44c1221b104ee02ec0235211f7ace3c88eb11a2 # v0.0.19
        with:
          provision: 'false'
          cmd: |
            set -ex
            uname -a
            cat /etc/issue
            pushd /host
            if [ -f "/var/lib/claudeinsight/btf/current.btf" ]; then  
                bash /host/testdata/test_gotls.sh 'sudo /host/claudeinsight/claudeinsight $claudeinsight_log_option --btf /var/lib/claudeinsight/btf/current.btf'
            else  
                bash /host/testdata/test_gotls.sh 'sudo /host/claudeinsight/claudeinsight $claudeinsight_log_option'
            fi
            popd

      - name: Test https
        uses: cilium/little-vm-helper@c44c1221b104ee02ec0235211f7ace3c88eb11a2 # v0.0.19
        with:
          provision: 'false'
          cmd: |
            set -ex
            uname -a
            cat /etc/issue
            pushd /host
            if [ -f "/var/lib/claudeinsight/btf/current.btf" ]; then  
                bash /host/testdata/test_https.sh 'sudo /host/claudeinsight/claudeinsight $claudeinsight_log_option --btf /var/lib/claudeinsight/btf/current.btf'
            else  
                bash /host/testdata/test_https.sh 'sudo /host/claudeinsight/claudeinsight $claudeinsight_log_option'
            fi
            popd

      - name: Test side
        uses: cilium/little-vm-helper@c44c1221b104ee02ec0235211f7ace3c88eb11a2 # v0.0.19
        with:
          provision: 'false'
          cmd: |
            set -ex
            uname -a
            cat /etc/issue
            pushd /host
            if [ -f "/var/lib/claudeinsight/btf/current.btf" ]; then  
                bash /host/testdata/test_side.sh 'sudo /host/claudeinsight/claudeinsight $claudeinsight_log_option --btf /var/lib/claudeinsight/btf/current.btf'
            else  
                bash /host/testdata/test_side.sh 'sudo /host/claudeinsight/claudeinsight $claudeinsight_log_option'
            fi
            popd

      - name: Test base
        uses: cilium/little-vm-helper@c44c1221b104ee02ec0235211f7ace3c88eb11a2 # v0.0.19
        with:
          provision: 'false'
          cmd: |
            set -ex
            uname -a
            cat /etc/issue
            if [ -f "/var/lib/claudeinsight/btf/current.btf" ]; then  
                bash /host/testdata/test_base.sh 'sudo /host/claudeinsight/claudeinsight $claudeinsight_log_option --btf /var/lib/claudeinsight/btf/current.btf'
            else  
                bash /host/testdata/test_base.sh 'sudo /host/claudeinsight/claudeinsight $claudeinsight_log_option'
            fi

      - name: Test filter by l3/l4 info
        uses: cilium/little-vm-helper@c44c1221b104ee02ec0235211f7ace3c88eb11a2 # v0.0.19
        with:
          provision: 'false'
          cmd: |
            set -ex
            uname -a
            cat /etc/issue
            if [ -f "/var/lib/claudeinsight/btf/current.btf" ]; then  
                bash /host/testdata/test_filter_by_l4.sh 'sudo /host/claudeinsight/claudeinsight $claudeinsight_log_option --btf /var/lib/claudeinsight/btf/current.btf'
            else  
                bash /host/testdata/test_filter_by_l4.sh 'sudo /host/claudeinsight/claudeinsight $claudeinsight_log_option'
            fi

      - name: Test kern evt
        uses: cilium/little-vm-helper@c44c1221b104ee02ec0235211f7ace3c88eb11a2 # v0.0.19
        with:
          provision: 'false'
          cmd: |
            set -ex
            uname -a
            cat /etc/issue
            if [ -f "/var/lib/claudeinsight/btf/current.btf" ]; then
                bash /host/testdata/test_kern_evt.sh 'sudo /host/claudeinsight/claudeinsight $claudeinsight_log_option --btf /var/lib/claudeinsight/btf/current.btf'
            else
                bash /host/testdata/test_kern_evt.sh 'sudo /host/claudeinsight/claudeinsight $claudeinsight_log_option'
            fi
